---
title: "Sobre"
---

João Victor Figueiredo Moreira é mestrando em Sociologia e bacharel em Ciências Sociais pela Universidade Federal de Minas Gerais (UFMG). Desenvolve pesquisas na interface entre mobilidade urbana, envelhecimento populacional e desigualdades socioespaciais, com foco na Região Metropolitana de Belo Horizonte. Integra o Centro de Estudos Urbanos (CEURB/UFMG) e atua em projetos voltados à análise de mobilidade de pessoas idosas.

Foi bolsista da Fundação de Amparo à Pesquisa do Estado de Minas Gerais (FAPEMIG) no projeto "Indicadores e diretrizes para a construção de uma política de mobilidade urbana inclusiva e sustentável para a população idosa", e do CNPq em pesquisa voltada às relações de gênero nos esportes eletrônicos. Atua também como analista de pesquisa no Instituto Ver, com experiência em elaboração de questionários, desenho amostral, análise de dados em R, SPSS e Excel.

Suas publicações incluem artigos e capítulos além de apresentações em congressos nacionais e internacionais.

