project:
  type: website
  output-dir: docs

website:
  title: "João V. F. Moreira"
  navbar:
    background: primary
    search: true
    left:
      - icon: house-door
        text: " "
        href: index.qmd
      - icon: person
        text: " "
        href: about.qmd
    right:
      - text: "🌐"
        menu:
          - text: "English"
            href: /index.html
          - text: "Português"
            href: /locales/pt/index.html
          - text: "Español"
            href: /locales/es/index.html
          - text: "Français"
            href: /locales/fr/index.html
      - icon: envelope
        href: mailto:joaovictorfigueiredo01@outlook.com
      - icon: github
        href: https://github.com/joaovsoc

format:
  html:
    theme: lux
    css: styles.css
    toc: true

language:
  default: en
  translations:
    pt: locales/pt
    es: locales/es
    fr: locales/fr
